job: extension
config:
  name: "YOUR_LORA_NAME"
  process:
    - type: 'sd_trainer'
      training_folder: "/root/ai-toolkit/modal_output"
      device: cuda:0
      trigger_word: "atelierai_sks_768"
      network:
        type: "lokr"
        linear: 16
        linear_alpha: 16
        network_kwargs:
          only_if_contains:
            - "transformer.single_transformer_blocks.9."
            - "transformer.single_transformer_blocks.25."
            - "transformer.transformer_blocks.5."
            - "transformer.transformer_blocks.15."
      save:
        dtype: float16
        save_every: 10000
        max_step_saves_to_keep: 4
        push_to_hub: true
        hf_private: true
        hf_repo_id: "YOUR_USERNAME/YOUR_MODEL_NAME"
      datasets:
        - folder_path: "/root/ai-toolkit/YOUR_DATASET"
          caption_ext: "txt"
          caption_dropout_rate: 0.0
          shuffle_tokens: false
          cache_latents_to_disk: false
          resolution: [768, 1024]
      train:
        batch_size: 1
        steps: {steps}
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        lr: 1e-3
        skip_first_sample: true
        disable_sampling: true
        ema_config:
          use_ema: true
          ema_decay: 0.99
        dtype: bf16
      model:
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: false
        low_vram: false
      sample:
        sampler: "flowmatch"
        sample_every: 1000
        width: 1024
        height: 1024
        prompts:
          - "cowboy wearing a denim jacket, atelierai_sks_768"
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 3.5
        sample_steps: 28